/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author MustafaR
 */
import Project.ConnectionProvider;
import java.sql.*;
import com.mysql.cj.util.StringUtils;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;



public class Quiz extends javax.swing.JFrame  {
    //public int questionID=1;
    public String answer;
    public int random = (int) ((Math.random() * (35-1))+1 );    
    public int random1;
    public int score;

    /**
     * Creates new form Quiz
     */
    public Quiz() {
        initComponents();
    }
    public Quiz(String str, int questionID) {
        
        initComponents();
        
       String questionId = Integer.toString(questionID);
        jLabel5.setText(str);
        jLabel6.setText(questionId);
        try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            Statement sm = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            Statement sr = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            Statement sq = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = st.executeQuery("select * from sozluk where id='"+random+"'");
            random = (int) ((Math.random() * (35-1))+1 );
            ResultSet rm = sm.executeQuery("select * from sozluk where id='"+random+"'");
            random = (int) ((Math.random() * (35-1))+1 );
            ResultSet rt = sr.executeQuery("select * from sozluk where id='"+random+"'");
            random = (int) ((Math.random() * (35-1))+1 );
            ResultSet rq = sq.executeQuery("select * from sozluk where id='"+random+"'");
            if (rs.first())
            {
                jLabel9.setText(rs.getString(2));
                random1 = (int) ((Math.random() * (5-1))+1 );
                System.out.println(random1);
                if (random1 == 1){
                    jRadioButton1.setText(rs.getString(3));
                    if (rm.first()) {
                         jRadioButton2.setText(rm.getString(3));
                    }
                    if (rt.first()) {
                         jRadioButton3.setText(rt.getString(3));
                    }
                    if (rq.first()) {
                         jRadioButton4.setText(rq.getString(3));
                    }
                }
                if (random1 == 2){
                    jRadioButton2.setText(rs.getString(3));
                    if (rm.first()) {
                         jRadioButton1.setText(rm.getString(3));
                    }
                    if (rt.first()) {
                         jRadioButton4.setText(rt.getString(3));
                    }
                    if (rq.first()) {
                         jRadioButton3.setText(rq.getString(3));
                    }
                }
                if (random1 == 3){
                    jRadioButton3.setText(rs.getString(3));
                    if (rm.first()) {
                         jRadioButton1.setText(rm.getString(3));
                    }
                    if (rt.first()) {
                         jRadioButton2.setText(rt.getString(3));
                    }
                    if (rq.first()) {
                         jRadioButton4.setText(rq.getString(3));
                    }
                }
                if (random1 == 4){
                    jRadioButton4.setText(rs.getString(3));
                    if (rm.first()) {
                         jRadioButton1.setText(rm.getString(3));
                    }
                    if (rt.first()) {
                         jRadioButton2.setText(rt.getString(3));
                    }
                    if (rq.first()) {
                         jRadioButton3.setText(rq.getString(3));
                    }
                }
               
            }

        } catch (Exception e) {
            JFrame jf = new JFrame();
                jf.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(jf, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quiz Time !");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 22, 373, 56));

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 200, 56));

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Mustafa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 373, 56));

        jLabel6.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 158, 56));

        jLabel7.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Question");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 158, 56));

        jLabel8.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Which is the synonym of");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 420, 56));

        jLabel9.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("something");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 250, 56));

        jRadioButton1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButton1MouseClicked(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, -1, -1));

        jRadioButton2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jRadioButton2.setText("jRadioButton1");
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

        jRadioButton3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jRadioButton3.setText("jRadioButton1");
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        jRadioButton4.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jRadioButton4.setText("jRadioButton1");
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        jButton1.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-close-96.png"))); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 600, 290, 90));

        jButton2.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/right.png"))); // NOI18N
        jButton2.setText("Next");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 600, 250, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
       try {
            Connection con = ConnectionProvider.getCon();
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            Statement sm = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet  rs = st.executeQuery("select id from questionid");
            ResultSet  rm = sm.executeQuery("select score from questionid");            
            String name = jLabel5.getText();
            int id = 1;
            int score = 0;
            if (rs.first()){
                id = rs.getInt(1);
                if (rm.first()) {
                    score = rm.getInt(1);
                    if (random1==1 && jRadioButton1.isSelected()) {
                        score = score + 1;   
                        PreparedStatement pm = con.prepareStatement("UPDATE questionid SET score=?");
                        pm.setInt(1, score);
                        pm.executeUpdate();
                    }
                    if (random1==2 && jRadioButton2.isSelected()) {
                        score = score + 1;   
                        PreparedStatement pm = con.prepareStatement("UPDATE questionid SET score=?");
                        pm.setInt(1, score);
                        pm.executeUpdate();
                    }
                    if (random1==3 && jRadioButton3.isSelected()) {
                        score = score + 1;   
                        PreparedStatement pm = con.prepareStatement("UPDATE questionid SET score=?");
                        pm.setInt(1, score);
                        pm.executeUpdate();
                    }
                    if (random1==4 && jRadioButton4.isSelected()) {
                        score = score + 1;   
                        PreparedStatement pm = con.prepareStatement("UPDATE questionid SET score=?");
                        pm.setInt(1, score);
                        pm.executeUpdate();
                    }
                    
                }
                if (id<10) {
                    id = id + 1;   
                    PreparedStatement ps = con.prepareStatement("UPDATE questionid SET id=?");
                    ps.setInt(1, id);
                    ps.executeUpdate();
                    String stf = String.valueOf(id);
                    jLabel6.setText(stf);
                    random = (int) ((Math.random() * (35-1))+1 );
                    setVisible(false);
                    //String string = new QuizStart().str;
                    new Quiz(name, id).setVisible(true);
                }
                else{
                    Statement sy = con.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
                    ResultSet  ry = sy.executeQuery("select score from questionid");
                    if (ry.first()) {
                        score = ry.getInt(1);
                        String scorer = String.valueOf(score);
                        PreparedStatement pm = con.prepareStatement("insert into players values(?,?)");
                        pm.setString(1, name);
                        pm.setString(2, scorer);
                        pm.executeUpdate();
                        
                        
                    }
                    JFrame jf = new JFrame();
                    jf.setAlwaysOnTop(true);
                    JOptionPane.showMessageDialog(jf,"Quiz Finished!");
                    setVisible(false);
                    new index().setVisible(true);
                }
                
            }
            
            
        } catch (Exception e) {
            JFrame jf = new JFrame();
            jf.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(jf, e);
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MouseClicked
        // TODO add your handling code here:   
    }//GEN-LAST:event_jRadioButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
